# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prepareCI:
    name: Prepare CI env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16
      - name: Set yarn version
        - run: yarn set version berry
        - run: yarn plugin import workspace-tools
        shell: bash
      - name: Cache ~/.cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('./yarn.lock') }}
      - name: Install
        run: yarn install --frozen-lockfile
        shell: bash

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepareCI
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn lint
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm install -g yarn


